### ISSUE TITLE
UI pages cause SCOM Console to close with unhandled exception (crash)

### ISSUE THREAD

**Issue by ChrisHeitkamp** [MPCatalog/scom-community-catalog-ui#2]
Symptom:
--------------
Open the "Discover Community Packs"  view causes the SCOM Console to crash with an unhanded exception. 

Description:
--------------
Before the crash a pop up screen shows up with:
"An error occurred while sending the request"
The crash is reproducible. 

Crash details are given below. 
Note that the Console on this machine does not have internet access, hence a prerequisite is not met. Still the console crashing is kind of unexpected...

SCOM Version: 2012 R2, UR12
MP Version: 1.0.2.0

Exception Details:
------------------
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'www.mpcatalog.net'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Community.ManagementPackCatalog.UI.Models.GitHubRepository.<PopulateClassFieldsFromResources>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Community.ManagementPackCatalog.UI.Models.GitHubRepository.<PopulateDataFromRepository>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Community.ManagementPackCatalog.UI.DiscoverCatalogPacks.PopulateCommunityManagementPackListFromGitHub(GitHubPackDetail[] packsToDisplay)
   at Community.ManagementPackCatalog.UI.DiscoverCatalogPacks..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateView(Object parent, Type viewType, IViewParameters viewParameters)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ViewConstructor.BeginShow(ShowViewContext showViewContext, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateNonRecyclableView(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateAndShowViewCore(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.ShowViewOperation.Begin(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.BeginShow(ShowViewContext showViewContext, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.ConsoleViewDisplayService.OpenViewJob(Object sender, ConsoleJobEventArgs args)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Console.ConsoleJobExceptionHandler.ExecuteJob(IComponent component, EventHandler`1 job, Object sender, ConsoleJobEventArgs args)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ConsoleJobsService.RunJob(ConsoleJobDescription jobDescription)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(ConsoleJobDescription jobDescription)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(IComponent jobOwner, EventHandler`1 jobMethod, EventHandler`1 errorHandler, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(IComponent jobOwner, EventHandler`1 jobMethod, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(EventHandler`1 jobMethod, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.ConsoleViewDisplayService.OpenView(String assemblyName, String typeName, String target, String item, String criteria, Object[] arguments)
   at Microsoft.EnterpriseManagement.Monitoring.Console.Common.ConsoleDisplayWrapper.OpenView(String assemblyName, String typeName, String target, String item, String criteria, Object[] arguments)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Console.MomViewsDisplay.OpenMomView(IComponent component, ManagementPackView view, String target, String item)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Administration.AdminTreeView.LaunchView(AdminTreeDataNode viewNode)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Administration.AdminTreeView.HandleNodeSelected(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

....
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by clarkd** [comment]
It looks like your SCOM server is struggling to access/resolve www.mpcatalog.net - do you have a firewall in place?

Are you able to browse to www.mpcatalog.net/CatalogRepo from your SCOM server? It should forward you to a GitHub page which will display an error but you should see the URL change.

**Comment by P2P-Nathan** [comment]
@ChrisHeitkamp , sorry for the delay on getting this fix in place.  A new build (detailed below) has been created that has more robust error handling, it should much more gracefully handle the lack of an internet connection.  Links to the beta version of the build are at the bottom of the comment.

The test build has been created that allows for the setting of a proxy via 3 registry keys.  Additionally it allows for a direct URL to be used for connection to GitHub, without the use of the MPCatalog.net redirect.

The keys can be seen in my branch at: [https://github.com/MPCatalog/scom-community-catalog-ui/blob/work/1.0.2.x-bug-fixes/Community.ManagementPackCatalog.UI/Models/GitHubRepository.cs#L114](https://github.com/MPCatalog/scom-community-catalog-ui/blob/work/1.0.2.x-bug-fixes/Community.ManagementPackCatalog.UI/Models/GitHubRepository.cs#L114)

Proxy configuration has a key for each of the following: 
 - proxyAddress
 - proxyUserName
 - proxyPassword

Repo URL configuration has a single key of:
 - GitHubRepoBase

**The updated version of the pack can be found here:**
[Community.ManagementPackCatalog.zip](https://github.com/MPCatalog/scom-community-catalog-ui/files/1497606/Community.ManagementPackCatalog.zip)

**Both registry configuration examples are available here:**
[Registry Key Configurations.zip](https://github.com/MPCatalog/scom-community-catalog-ui/files/1497613/Registry.Key.Configurations.zip)

**Comment by P2P-Nathan** [comment]
The beta release for this build is at the below url, the testing I have performed has passed, but I do not have an actual proxy environment and am unable to do a full functionality test.

[1.0.2.0 beta release](https://github.com/MPCatalog/scom-community-catalog-ui/releases/tag/v1.0.2.0-beta)

**Comment by Juanito99** [comment]
hi,

tested with 1.0.2.1 - no success.
![image](https://user-images.githubusercontent.com/11002556/33365327-d3dc8412-d522-11e7-9275-cfd76ad2a2b8.png)

Same error as before. - No Exception, console keeps functioning.

This is my registry setting. - Correct?
![image](https://user-images.githubusercontent.com/11002556/33365288-b58b533a-d522-11e7-9010-2fb1bbed4b6a.png)

Ruben

**Comment by P2P-Nathan** [comment]
Thank you for testing,
I do not have a proxy in my environment and was not able to test as well as
I would have liked.  I will look through the code again and may need to
find a sample proxy server to test with.
-Nathan

**Comment by Juanito99** [comment]
Another option could be adding debug code to your solution. I am happy to run it and provide trace information.

Let me know :-)

**Comment by P2P-Nathan** [comment]
The code is instrumented with ETW logging, it can be viewed with perfview,
as well as a custom tool I've written to make it quicker to trace.

I'm out of the office for the night but I'll make sure tracing is in all
the necessary places tomorrow and send over some better details.

Thanks,
Nathan

**Comment by Juanito99** [comment]
Sure, no problem. - Have a good rest :-)

**Comment by ronaldbckl** [comment]
Just i tip for others. I just found out i had the same errors while the sites mentioned are reachable.
It turned out that this pack will not work if you run your scom console from a non-managementserver. From a managementserver it works ok.
