### ISSUE TITLE
Discover Community Packs not working - System.AggregateException unable to resolve the index location from http://www.mpcatalog.net/CatalogRepo

### ISSUE THREAD

**Issue by P2P-Nathan** [MPCatalog/scom-community-catalog-ui#4]
_From @Juanito99 on October 25, 2017 1:2_

Hi,

our SCOM is sitting behind a proxy server. It is maintained in the server configuration:

![image](https://user-images.githubusercontent.com/11002556/31975321-ebff628e-b962-11e7-94d6-b1cc5bcf29d3.png)

After clicking on 'Discover Community Packs' an exception window is thrown and the SCOM console crashes.

![image](https://user-images.githubusercontent.com/11002556/31975333-0b7a3472-b963-11e7-9c68-84476a36d4af.png)

![image](https://user-images.githubusercontent.com/11002556/31975338-11f187e2-b963-11e7-992c-d398311577d5.png)

The text goes as follows:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: Unable to resolve the index location from http://www.mpcatalog.net/CatalogRepo
   at Community.ManagementPackCatalog.UI.Models.GitHubRepository.<PopulateClassFieldsFromResources>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.ManagementPackCatalog.UI.Models.GitHubRepository.<PopulateDataFromRepository>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Community.ManagementPackCatalog.UI.DiscoverCatalogPacks.PopulateCommunityManagementPackListFromGitHub(GitHubPackDetail[] packsToDisplay)
   at Community.ManagementPackCatalog.UI.DiscoverCatalogPacks..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateView(Object parent, Type viewType, IViewParameters viewParameters)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ViewConstructor.BeginShow(ShowViewContext showViewContext, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateNonRecyclableView(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateAndShowViewCore(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.ShowViewOperation.Begin(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.BeginShow(ShowViewContext showViewContext, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.ConsoleViewDisplayService.OpenViewJob(Object sender, ConsoleJobEventArgs args)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Console.ConsoleJobExceptionHandler.ExecuteJob(IComponent component, EventHandler`1 job, Object sender, ConsoleJobEventArgs args)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ConsoleJobsService.RunJob(ConsoleJobDescription jobDescription)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(ConsoleJobDescription jobDescription)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(IComponent jobOwner, EventHandler`1 jobMethod, EventHandler`1 errorHandler, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(IComponent jobOwner, EventHandler`1 jobMethod, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowJobsService.RunJob(EventHandler`1 jobMethod, Object[] arguments)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.ConsoleViewDisplayService.OpenView(String assemblyName, String typeName, String target, String item, String criteria, Object[] arguments)
   at Microsoft.EnterpriseManagement.Monitoring.Console.Common.ConsoleDisplayWrapper.OpenView(String assemblyName, String typeName, String target, String item, String criteria, Object[] arguments)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Console.MomViewsDisplay.OpenMomView(IComponent component, ManagementPackView view, String target, String item)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Administration.AdminTreeView.LaunchView(AdminTreeDataNode viewNode)
   at Microsoft.EnterpriseManagement.Mom.Internal.UI.Administration.AdminTreeView.HandleNodeSelected(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Thanks in advance

Ruben

_Copied from original issue: MPCatalog/scom-community-catalog#13_

**Comment by P2P-Nathan** [comment]
_From @Juanito99 on October 25, 2017 6:31_

Update: If I configure the proxy server using Internet Explorer it works. - So feature request:
Please consider the proxy configuration instead of the local Internet Explorer

Thanks ;-)

**Comment by P2P-Nathan** [comment]
Thanks for the the update, I'll add that as a work around to the documentation for others trying to access the packs through a proxy.

I've also noted the feature request, and will try to make the error a little more friendly :-)  Taking the console down seems a little excessive.

**Comment by P2P-Nathan** [comment]
#2 Covers the exception here, once #2 is closed I'll create a new feature request for the proxy functionality.

**Comment by P2P-Nathan** [comment]
A new test build has been created that allows for the setting of a proxy via 3 registry keys.  Additionally it allows for a direct URL to be used for connection to GitHub, without the use of the MPCatalog.net redirect.

The keys can be seen in my branch at: [https://github.com/MPCatalog/scom-community-catalog-ui/blob/work/1.0.2.x-bug-fixes/Community.ManagementPackCatalog.UI/Models/GitHubRepository.cs#L114](https://github.com/MPCatalog/scom-community-catalog-ui/blob/work/1.0.2.x-bug-fixes/Community.ManagementPackCatalog.UI/Models/GitHubRepository.cs#L114)

Proxy configuration has a key for each of the following: 
 - proxyAddress
 - proxyUserName
 - proxyPassword

Repo URL configuration has a single key of:
 - GitHubRepoBase

**The updated version of the pack can be found here:**
[Community.ManagementPackCatalog.zip](https://github.com/MPCatalog/scom-community-catalog-ui/files/1497606/Community.ManagementPackCatalog.zip)

**Both registry configuration examples are available here:**
[Registry Key Configurations.zip](https://github.com/MPCatalog/scom-community-catalog-ui/files/1497613/Registry.Key.Configurations.zip)

**Comment by P2P-Nathan** [comment]
The beta release for this build is at the below url, the testing I have performed has passed, but I do not have an actual proxy environment and am unable to do a full functionality test.

[1.0.2.0 beta release](https://github.com/MPCatalog/scom-community-catalog-ui/releases/tag/v1.0.2.0-beta)

**Comment by Juanito99** [comment]
Hi,

good news; the console is not crashing any more when no connection is possible :)

1.
Could you change the condition to also accept proxy servers without authentication requirement?
 if (proxyAddress != null && proxyUserName == null && proxyPassword == null)
I don't need UserName and Password.


2. 
In the final version, could you move the keys to HKLM?  Current it's HCU, that makes it hard because more than one guy is checking with SCOM.

Thank you  :-)

**Comment by P2P-Nathan** [comment]
If you remove the registry keys for Password and Username the code should
only use the URL, see
https://github.com/MPCatalog/scom-community-catalog-ui/blob/work/1.0.2.x-bug-fixes/Community.ManagementPackCatalog.UI/Models/GitHubRepository.cs#L122

As for the HKLM and HCU, I was stuck between the two for security reasons,
but that may not be something of concern.
I can make the updates to HKLM, that sounds good to me.

-Nathan

**Comment by P2P-Nathan** [comment]
@Juanito99, the registry check now looks for configuration in HKLM.  HKCU can still be used if user-level settings are needed (proxy password and username come to mind.)  If a property is set at both HKLM and HKCU the HKCU property will be used.

Excluding a proxyUserName and proxyPassword still allows for the proxy to be used without authentication.

A 1.0.2.1 build is below with this code updated.
[Community.ManagementPackCatalog.zip](https://github.com/MPCatalog/scom-community-catalog-ui/files/1506443/Community.ManagementPackCatalog.zip)

Thanks for the quick feedback,

**Comment by Juanito99** [comment]
@P2P-Nathan : Sorry, did it wrong. - Proxy setting is not working in our environment.
I can only access it when adding the proxy information to the Internet Explorer configuration.
Tried to set the proxy using 'netsh', but doing so is also not considered.

Let me know if I can help to trouble-shoot this issue.

**Comment by P2P-Nathan** [comment]
Thanks for the update @Juanito99 , I'll take a look at getting a proxy setup for testing.

**Comment by beigewell** [comment]
I see this a lot and is primarily due to the redirect to github from the initial url. We are doing ssl inspection etc so things like this get picked up! Is there anyway it could just point to github without the mpcatalog url?

**Comment by P2P-Nathan** [comment]
@beigewell , Sorry for the delay.  

You can set a direct URL by creating a key named "GitHubRepoBase" at HKEY_LOCAL_MACHINE\Software\MPCatalog.  Set the value to "https://raw.githubusercontent.com/MPCatalog/scom-community-catalog/master/"

Could you please see if this works for you?  

Thanks,
Nathan Foreman

**Comment by beigewell** [comment]
Worked a treat thank you much better under HKLM
